### ISSUE TITLE
실험에서 사용한 모델들의 대한 정보를 논문에서 명시해야할까요?

### ISSUE THREAD

**Issue by 201411108** [201411108/paper#4]
본문에서는 모델들의 구조와 하이퍼 파라미터들은 크게 중요하지 않다고 지속적으로 말하고 있습니다.
그리고 ResNet과 VGG의 경우 `torchvision.models`에서 제공하는 것을 불러서 사용하고 있습니다.

4.1.절에서 실험에서 사용한 모델들에 대한 간단한 소개를 하고 있는데 모델들의 구조에 대한 그림 또는 표를 첨부할 필요가 있을지에 대한 여부를 여쭤보고 싶습니다.

**Comment by 201411108** [comment]
추가로 사용한 데이터 셋 및 적대적 데이터 셋 예시도 그림으로 표현하려고 하고 있는데 각 데이터 셋의 클래스가 서로 상이하여 본문 내가 아닌 Appendix과 같이 따로 빼려고 생각해봤는데 이에 대해서도 의견 주시면 감사하겠습니다 !

**Comment by elvenwhite** [comment]
모델에 대한 그림은 넣을 필요 없겠고요, 이미지 예시는 분량이 너무 많지 않다면 본문 중에 넣는 것이 어떨까 합니다. 

Jongdae Han / 한종대 
Elvenwhite

**Comment by 201411108** [comment]
네 ! 알겠습니다.
데이터 셋이 갖고 있는 모든 라벨에 대한 예시를 보여줄 필요는 없을까요 ?

**Comment by elvenwhite** [comment]
네 일부 라벨만 보여주면 되겠네요. 

Jongdae Han / 한종대 
Elvenwhite
